name: @NAME@
description: Locks for chests
depend: [MessageManager]
version: @VERSION@
author: @AUTHOR@
main: @MAIN@
commands:
    'simplelocks:lock':
        description: Manage locks
        usage: |
            /<command> - Show lock status
            /<command> (+|-) <Name> - Add or remove access
