name: SimpleLocks
version: @VERSION@
description: Locks for chests
author: EdGruberman (ed@rjump.com)
website: http://github.com/EdGruberman/SimpleLocks
main: edgruberman.bukkit.simplelocks.Main
loadbefore: [SimpleRegions]
commands:
    'simplelocks:describe':
        aliases: [lock.describe, 'lock?', 'l?']
        description: Show lock information for targeted block
        permission: simplelocks.describe
        usage: '§f-> §7Usage: §b/<command>'
    'simplelocks:grant':
        aliases: [lock.grant, lock+, l+]
        description: Grant explicit lock access to targeted block
        permission: simplelocks.grant
        usage: '§f-> §7Usage: §b/<command> <Name>'
    'simplelocks:revoke':
        aliases: [lock.revoke, lock-, l-]
        description: Revoke explicit lock access from targeted block
        permission: simplelocks.revoke
        usage: '§f-> §7Usage: §b/<command> <Name>'
    'simplelocks:break':
        aliases: [lock.break]
        description: Remove lock from targeted block
        permission: simplelocks.break
        usage: '§f-> §7Usage: §b/<command>'
    'simplelocks:reload':
        description: Reload plugin configuration
        permission: simplelocks.reload
        usage: '§f-> §7Usage: §b/<command>'
permissions:
    simplelocks.user:
        description: Can create new locks and edit accessible locks
        default: true
        children:
            simplelocks.create: true
            simplelocks.lock.describe: true
            simplelocks.lock.grant: true
            simplelocks.lock.revoke: true
    simplelocks.admin:
        description: Can use administrative features of SimpleLocks plugin
        default: op
        children:
            simplelocks.user: true
            simplelocks.lock.break: true
            simplelocks.override: true
            simplelocks.reload: true
    simplelocks.create:
        description: Can create new locks
        default: false
    simplelocks.lock.describe:
        description: Can use lock.describe command on any lock
        default: false
    simplelocks.lock.grant:
        description: Can use lock.grant command if lock owner
        default: false
    simplelocks.lock.revoke:
        description: Can use lock.revoke command if lock owner
        default: false
    simplelocks.lock.break:
        description: Can use lock.break command on any lock
        default: false
    simplelocks.override:
        description: Can access or edit any lock even if not owner
        default: false
    simplelocks.reload:
        description: Can use reload command
        default: false