name: @NAME@
description: Locks for chests
depend: [MessageManager, AccessControl]
version: @VERSION@
author: @AUTHOR@
main: edgruberman.bukkit.simplelocks.Main
commands:
    lock:
        description: Manage locks
        usage: |
            /<command> - Show lock status for block targeted
            /<command> (+|-) <Name> - Add or remove access
            [Server Operators]
            /<command> owner <Owner> - Change lock owner
            /<command> break - Remove the lock
