name: @NAME@
description: Locks for blocks.
depend: [MessageManager, AccessControl]
version: @VERSION@
author: @AUTHOR@
main: edgruberman.bukkit.simplelocks.Main
commands:
    lock:
        description: Manage locks on blocks.
        usage: |
            /<command> - Show the current lock status for block targeted.
            /<command> (+|-) <Name> - Add or remove <Name> with access.
            [Server Operators]
            /<command> owner <Owner> - Change lock owner.
            /<command> break - Remove the lock.
